### ISSUE TITLE
New AWS gem breaks ec2-blackout

### ISSUE THREAD

**Issue by ampedandwired** [srbartlett/ec2-blackout#4]
Version 2 of aws-sdk changes the namespace from `AWS` to `Aws`. This breaks ec2-blackout. Probably be a good idea to put some version constraints on the gemspec to avoid major upgrades breaking stuff. I'll try and do up a PR when I get some time. For now the workaround is to `gem install aws-sdk --version '< 2.0'`

More info here: http://ruby.awsblog.com/post/TxFKSK2QJE6RPZ/Upcoming-Stable-Release-of-AWS-SDK-for-Ruby-Version-2

**Comment by srbartlett** [comment]
Thanks, mate.  Good pick up.  Happy to accept a PR otherwise I'll try to pick it up in the next week or so...
