### ISSUE TITLE
Request to selectively starting instances

### ISSUE THREAD

**Issue by sanjaymunjal** [srbartlett/ec2-blackout#5]
Hi,
Thanks for the tool. We need bit of starting order during starting the instance again. Wondering if you can allow selectively turning on based upon tags. Also if allow for re-registring the instances which are part of ELB so that when they come back then ELB can perform health checks again.
We are using it for our staging environment.
Regards.
Sanjay

**Comment by srbartlett** [comment]
Hi @sanjaymunjal 

This feature is now available in version 0.0.10

Let me know if you have any problems
