### ISSUE TITLE
Include by Tag for ec2-blackout off command

### ISSUE THREAD

**Issue by emoshaya-cognito** [srbartlett/ec2-blackout#7]
Are you able to expand the commands for ec2-blackout off?

I need to be able to only switch on certain instances by tag name.

ec2-blackout off --include-by-tag 'Name=myapp.*'

**Comment by srbartlett** [comment]
Not at this stage.  `ec2-backout off` will start instances that it previously stopped. 

Happy to accept a PR

**Comment by srbartlett** [comment]
Hi @emoshaya-cognito 

This feature has been implemented in version 0.0.10

Let me know if you have any questions.
